version: '3.9'
services:
  db:
    container_name: dev_db
    image: postgres:13.3-alpine
    ports:
      - 5432:5432
    volumes:
      - dbdata:/var/lib/postgresql/data
    env_file:
      - .env
  adminer:
    container_name: adminer
    image: adminer:4.7.5
    ports:
      - 8080:8080

volumes:
  dbdata: null
