name: Deploy

on:
  push:
    branches: 
      - main

jobs:
  deploy:
    name: deploy_to_vps
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Create .env file
        run: |
          echo "POSTGRES_USER=${{ secrets.POSTGRES_USER }}" > .env
          echo "POSTGRES_PASSWORD=${{ secrets.POSTGRES_PASSWORD }}" >> .env
          echo "POSTGRES_HOST=${{ secrets.POSTGRES_HOST }}" >> .env
          echo "POSTGRES_DB=${{ secrets.POSTGRES_DB }}" >> .env
          echo "TZ=\"Asia/Tokyo\"" >> .env
          echo "SECRET_KEY=${{ secrets.SECRET_KEY }}" >> .env
      - uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_KEY }}
          name: id_sasami
          known_hosts: ${{ secrets.KNOWN_HOSTS }}
          config: |
            Host sasami
              HostName sasami.pigeons.house
              User hato_yashiki
              Port 14217
              IdentityFile ~/.ssh/id_sasami
      - name: deploy
        run: bash deploy.sh
